site_name: Omniverse Kit Cheat Sheet
site_description: "Kurzreferenz und Notizen rund um Omniverse Kit, USD & omni.ui"
# Passe das an, sobald das Repo existiert:
repo_url: https://github.com/perfectproducts/omniverse_kit_cheat_sheet
repo_name: perfectproducts/omniverse-kit-cheat-sheet

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - navigation.sections
    - toc.integrate

nav:
  - Home: index.md
  - UI:
        - Dialogs:
            - File Dialogs: cheatsheets/UI/file_dialogs.md
  - Work with:
    - Prims: cheatsheets/prims.md
    - Python: cheatsheets/python.md
    - AI Helpers: cheatsheets/ai_helpers.md

  - Resources:
    - Collections: cheatsheets/resources_collections.md
  
  
plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.snippets